#+title: Book Review: Cross Purposes, by Jonathan Rauch
#+date: 2025-04-29

* Synopsis
Rauch, a non-Christian, summarizes the core teachings of Jesus as the following:
- Forgive each other
- Serve the marginalized
- Don't be afraid

He claims that these teachings have historically been vital for the success of the United States as a democracy.

Christianity is divided by Rauch into three camps:
- Thin Christianity :: a watered-down version of Christianity that does not make demands of its adherents
- Sharp Christianity :: a politicized, cultural Christianity that trades commitment to the teachings of Jesus for political power
- Thick Christianity :: Christianity that maintains both its commitments to the teachings of Jesus and liberal democracy

* Is it true?
Although I think that Rauch's thesis is interesting and contains valuable lessons for Americans about the importance of Christianity to our democracy, I was left asking myself how did "thin" and "sharp" Christianity develop? Who or what is to blame? As with most decades-long cultural and historical movements, I think this one was probably overdetermined.
